"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/admin";

const slug = z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use letras minúsculas, números e hífens.");
const postSchema = z.object({ title:z.string().trim().min(2), slug, status:z.enum(["draft","scheduled","published","archived"]), summary:z.string().trim().optional(), content:z.string().trim().min(1), featured:z.boolean(), publishedAt:z.string().optional(), seoTitle:z.string().trim().optional(), seoDescription:z.string().trim().optional() });
const partnerSchema = z.object({ name:z.string().trim().min(2), slug, shortDescription:z.string().trim().optional(), content:z.string().trim().optional(), websiteUrl:z.string().trim().url().optional().or(z.literal("")), affiliateUrl:z.string().trim().url().optional().or(z.literal("")), coupon:z.string().trim().optional(), active:z.boolean(), featured:z.boolean(), sortOrder:z.coerce.number().int().min(0) });
function read(formData:FormData, key:string){return String(formData.get(key) ?? "");}
function checked(formData:FormData, key:string){return formData.get(key)==="on";}
function errorMessage(error:unknown){return error instanceof Error ? error.message : "Não foi possível salvar.";}

export async function savePost(formData: FormData) { const parsed=postSchema.safeParse({title:read(formData,"title"),slug:read(formData,"slug"),status:read(formData,"status"),summary:read(formData,"summary"),content:read(formData,"content"),featured:checked(formData,"featured"),publishedAt:read(formData,"publishedAt"),seoTitle:read(formData,"seoTitle"),seoDescription:read(formData,"seoDescription")}); if(!parsed.success) throw new Error(parsed.error.issues[0]?.message); const supabase=await requireAdmin(); const id=read(formData,"id"); const data={title:parsed.data.title,slug:parsed.data.slug,status:parsed.data.status,summary:parsed.data.summary||null,content:{html:parsed.data.content},featured:parsed.data.featured,published_at:parsed.data.publishedAt|| (parsed.data.status==="published"?new Date().toISOString():null),seo:{title:parsed.data.seoTitle,description:parsed.data.seoDescription},updated_at:new Date().toISOString()};const result=id?await supabase.from("blog_posts").update(data).eq("id",id):await supabase.from("blog_posts").insert(data);if(result.error)throw new Error(result.error.code==="23505"?"Este slug já está em uso.":errorMessage(result.error));revalidatePath("/");revalidatePath("/blog");redirect("/admin/blog"); }
export async function savePartner(formData: FormData) { const parsed=partnerSchema.safeParse({name:read(formData,"name"),slug:read(formData,"slug"),shortDescription:read(formData,"shortDescription"),content:read(formData,"content"),websiteUrl:read(formData,"websiteUrl"),affiliateUrl:read(formData,"affiliateUrl"),coupon:read(formData,"coupon"),active:checked(formData,"active"),featured:checked(formData,"featured"),sortOrder:read(formData,"sortOrder")||"0"});if(!parsed.success)throw new Error(parsed.error.issues[0]?.message);const supabase=await requireAdmin();const id=read(formData,"id");const data={name:parsed.data.name,slug:parsed.data.slug,short_description:parsed.data.shortDescription||null,content:{body:parsed.data.content},website_url:parsed.data.websiteUrl||null,affiliate_url:parsed.data.affiliateUrl||null,coupon:parsed.data.coupon||null,active:parsed.data.active,featured:parsed.data.featured,sort_order:parsed.data.sortOrder,updated_at:new Date().toISOString()};const result=id?await supabase.from("partners").update(data).eq("id",id):await supabase.from("partners").insert(data);if(result.error)throw new Error(result.error.code==="23505"?"Este slug já está em uso.":errorMessage(result.error));revalidatePath("/");revalidatePath("/parceiros");redirect("/admin/parceiros"); }
export async function deleteRecord(formData:FormData){const table=read(formData,"table");const id=read(formData,"id");if(!["projects","blog_posts","partners"].includes(table)||!id)throw new Error("Operação inválida.");const supabase=await requireAdmin();const {error}=await supabase.from(table).delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath("/");revalidatePath(`/${table==="projects"?"portfolio":table==="blog_posts"?"blog":"parceiros"}`);redirect(`/admin/${table==="projects"?"portfolio":table==="blog_posts"?"blog":"parceiros"}`);}
